spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  security:
    user:
      name: test
      password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    encoding:
      force-response: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
